### ISSUE TITLE
Make resume template sections modular

### ISSUE THREAD

**Issue by dcolli23** [dcolli23/resumaker#4]
# Description

One annoyance that I have is having to create a new template for each little tweak that I want to make to a resume's structure. Instead, it would be incredibly convenient to be able to compose sections into one template.

However, I'm not sure how easy this will be as I've not worked with DOCX files in Python much and I know their structure isn't trivial.

# Tasks

- [x] Determine how to compose two or more DOCX sections (loaded from separate files) into one `docxtpl.DocxTemplate` object.
- [x] Restructure the `templates` directory such that we have different directories for each variation of a section we'd want.
- [x] Add a method and directory (name TBD) for specifying which sections we'd like to compose and in what order.
  - I could see both JSON and YAML as appropriate file formats. We're already using YAML so this may be the best choice for consistency.
- [x] Consider specifying the section composition and other arguments (e.g. output name) in one file such that we only have to run `python -m resumaker job_specification.yaml` for each job.
  - I would argue that this helps with clutter in the output directory.
- [ ] Consider incorporating `pydoit` into the pipeline to make multiple resumes simultaneously and compare how different sections look.
